### ISSUE TITLE
Use Lat/Lon as one of the factors for fuzzy scoring

### ISSUE THREAD

**Issue by riordan** [pelias/fuzzy-tester#12]
One of the things that we care a lot about is "is this the right location". Right now, our testsuite doesn't take the location of the place into account, but instead relies on matching the labels of documents it knows to be correct.

But often there are several entries for a single place, an artifact of us importing from multiple data sources and only checking for duplication within the dataset. These documents are of varying quality, but all that matters to the user is "Is the place right".

In addition to these criteria, we should incorporate comparisons of distance from the "correct" document as well.

One possibility of how to consider this is to calculate distance from the "correct" target document for each query and have a gradient for scoring [e.g 0-10m, 10-30m, 30-100m, 500m-2k, 2k+] where the closer it is to the target the higher the score.

**Comment by missinglink** [comment]
:+1:

**Comment by orangejulius** [comment]
Fixed in #33
