### ISSUE TITLE
allow expected properties to be object or array

### ISSUE THREAD

**Issue by orangejulius** [pelias/fuzzy-tester#18]
Currently, if it's an array of size 1 (or more) everything is good. but simply an object fails.

**Comment by riordan** [comment]
@orangejulius Still an issue?

**Comment by orangejulius** [comment]
Yeah, really just a minor improvement I'll get to eventually.

**Comment by vesameskanen** [comment]
Already merged pull request #33 should fix this.

**Comment by orangejulius** [comment]
Indeed it does.
