### ISSUE TITLE
Email output generator is broken

### ISSUE THREAD

**Issue by orangejulius** [pelias/fuzzy-tester#30]
The email output generator does not handle the now recursive structure of test results, so trying to send test results with that output generator will result in a crash.
- [ ] Unify output code from the email and terminal output generator where possible
- [ ] Refactor the output generators so they are more testable
- [ ] Add some tests for the various output generators
- [ ] Make sure none of the output generators have trouble with the current result format

**Comment by riordan** [comment]
Now not blocking anything. To tackle soon after done with WoF Milestone.
