### ISSUE TITLE
ExponentialBackoff not working?

### ISSUE THREAD

**Issue by missinglink** [pelias/fuzzy-tester#7]
I've been playing with `ExponentialBackoff` and I'm not sure that how's its implemented in `exec_test_suite.js` is the expected behaviour.

The `milliseconds` param passed to `setInterval` is only evaluated once, so calls to `.decreaseBackoff();` seem to have no effect?

Need to confirm with @orangejulius maybe I'm not reading this correctly, see the test case below, when I set the backoff to `250` _after_ calling `setInterval` it has no effect.

``` javascript
// test to check that dynamically changing the backoff value
// effects the frequency setInterval triggers it's callback
test.test( 'functional test', function(t) {

    var counter = 0, interval,
        eb = new ExponentialBackoff();

    eb.backoff = 50; // set default

    var each = function(){
        counter++;
    };

    var end = function(){
        clearInterval( interval );
        t.equal( counter, 1000 / 250 );
        t.notEqual( counter, 1000 / 50 );
        t.end();
    };

    interval = setInterval( each, eb.getBackoff() );
    each(); // fire one off immediately

    setTimeout( end, 1000 );

    // change backoff to 250ms
    eb.backoff = 250;

});
```

**Comment by orangejulius** [comment]
Doh, you're right. This area of the code is one I've spent the least amount of time in. I'll make it better.
